### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Agost15** [ilscipio/scipio-erp#15]
I have a problem when install in Windows 10

This is the log
_"classes:
  [javac18] Compiling 152 source files to C:\scipio-erp\framework\entity\build\classes
  [javac18] warning: [options] bootstrap class path not set in conjunction with -source 8
  [javac18] C:\scipio-erp\framework\entity\src\org\ofbiz\entity\serialize\XmlSerializer.java:48: error: package javax.xml.bind does not exist
  [javac18] import javax.xml.bind.DatatypeConverter;
  [javac18]                      ^
  [javac18] 1 error
  [javac18] 1 warning

BUILD FAILED
C:\scipio-erp\build.xml:782: The following error occurred while executing this line:
C:\scipio-erp\build.xml:812: The following error occurred while executing this line:
C:\scipio-erp\macros.xml:394: The following error occurred while executing this line:
C:\scipio-erp\common.xml:81: Compile failed; see the compiler error output for details.

Total time: 1 minute 25 seconds
"_
I don´t know what I must do
Thanks in advance
Angels

**Comment by pplx** [comment]
You can try this (takes awhile):
`ant lib-clean lib-clean-cache-full build`

But most likely an issue with the JDK. What is your JDK version?

**Comment by madppiper** [comment]
Hi Agost15, 

and thank you for bringing this up: your post literally started a heated debate internally. 

So what's most likely the cause of your issue is that your Java JDK version is 11 or higher. Java switched to a modular architecture in 11 and therefore doesn't find some of the packages anymore. The error you are seeing is a cause of it. 

Scipio ERP is still largely targeted towards Java 8, which was the last major JDK version before 11 was released last year. The adoption of 11 is still rather low in the market, which is why it hasn't been ported for 2.0.0. Here's an interesting article on adoption rate: https://www.infoq.com/news/2018/12/java-2019-predictions.

Although we plan on getting Scipio compatible with Java 11 and above asap, it will take some time before it is being rolled out on Github. In the meanwhile I would recommend to downgrade to Java 8 or install java 8 alongside your current jdk in case you have other applications that require java 11. In case of the latter, you would need to modify the start.bat and build.xml files and manually replace the the %JAVA_HOME% variable with your java8 directory.

Sorry that you had to go through this. Unfortunately, we are really stuck as developers in this, as Java introduced the modular structure in between major releases and adoption has been so low that it has not really been a concern for a long while.

**Comment by Agost15** [comment]
Don't worry ;). 
I already installed the 8 but I still can not finish the installation. How can I see the log?
Change in specifications the java, delete "or higuer" ;)
Thanks for this great job!!!
I hope to enjoy it soon

**Comment by madppiper** [comment]
You can find the logs under runtime/logs/console.log and error.log
