### ISSUE TITLE
Remove not working/non-essential OFBiz code

### ISSUE THREAD

**Issue by PierreSmits** [ilscipio/scipio-erp#2]
Currently there is a lot of not working/non-essential OFBiz code in the repo. The not working code should be removed, and the non-essential code should be disentangled.

**Comment by madppiper** [comment]
Hi Pierre,

could you give an example of what you mean by "not working/not-essential OFBiz code" ? We do have quite some code left, which we marked with "SCIPIO: ToDo - Remove" or similar statements in the files. Those are often carried along, as it makes it easier to merge with OFBiz code. Since we want to remain compatible as long as possible, this is something that is actually desired at the moment. 

Is that what you had in mind, or do you refer to other aspects?

Thanks.
Paul

**Comment by PierreSmits** [comment]
One perfect example is the code regarding the3rd party payment solution 'ideal', which has never worked.

**Comment by madppiper** [comment]
Well, the idea is good. Could you perhaps a list of removable parts? Then we could discuss the benefits here.

**Comment by PierreSmits** [comment]
Well.... Let us start with the discussion regarding the removal of the 3rd party payment solution 'ideal'.

**Comment by madppiper** [comment]
I doubt there is too much to be discussed. 

If something isn't completely done, we should either remove or fix. I fear, however, that at the moment we got our hands busy working on other aspects of the software, so removing code is not too high on our list. We will have to reimplement the payment methods in particular, soon. 

Anyway, besides the discussion, a list of aspects you feel are "redundant" or "broken" would help us immensely. That way it is easier to put it on one of the future releases. Feel free to create individual tickets here, too, if you want to track progress on it.

**Comment by madppiper** [comment]
The ongoing discussion will be moved to the forum: http://forum.scipioerp.com/

I am closing the topic here, as it is not really a bug.
