### ISSUE TITLE
last update - still continued?

### ISSUE THREAD

**Issue by punkyard** [ilscipio/scipio-erp#42]
hi
SCIPIO seems a great ERP!
last update was in 2019, is it still maintained?
🤞

**Comment by madppiper** [comment]
Hey,

Glad you asked - yes absolutely!

We just haven't made it an official release yet, as we have worked so hard on many major changes that are all adding at the same time (new annotation based service definitions, major changes to the CMS, various add-ons, a new Bulma based default theme etc etc).

There's going to be a release coming shortly.
If you take a look at the news from our website you'll also see how busy we've all been with these changes, so bear with us :)

**Comment by madppiper** [comment]
So for now we recommend to go with the master/main branch and take it from there. It is stable :)

**Comment by punkyard** [comment]
nice to read! so you reckon the 2019 version of scipio is safe enough to be installed today.
Quid of the docker image? You still don't recommend to use scipio with docker?

**Comment by madppiper** [comment]
You can use the 2019 release just fine,it's been deployed several times on production systems.

We do encourage you to fork from the main branch, however, and update from there occasionally. 

Like I said, the 3.0 release will be coming out shortly and it's been years in between, so master is probably a better candidate by now. 

That said, in the future we will probably move away from long release cycles and rather tag releases more often. Simply because otherwise er fall into the trap that we keep adding new things (as we did now).

You can use Scipio in docker too. We got a docker branch that sets you right up. So that's all good by us. Really depends on your own CI flow.

**Comment by madppiper** [comment]
I have to add: in most cases you really do want to fork and regularly pull from us, simply because you will eventually want to add your own application and modifications to it.

If you add your own code in customs apps under hot-deploy, you won't really have to deal with difficult merges at all (except for the occasional properties file you have changed on your end to fit your need better, like cache.properties or default.properties).

So it becomes easier to stay up to date and really turn the system into your own.

**Comment by punkyard** [comment]
hey thanks a lot @madppiper for all those information and your concern
i'm afraid i'm not ready yet to do so, cause i've never done this
I usually use Portainer to deploy apps, but I'm not competent to fork, update, personnalise ..
I can just take things the way they are, and work around their installation
I guess I need to update my skills to be able to use SCIPIO once !

thanks again ✌️
